# -*- coding: utf-8 -*-
"""Lesson8game_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvbheTddeafWukjpZnhW3uyIicERvbMr
"""

import random

def fun_game(die_sides):
  """This is a game to roll a user sided die 5 times"""
  die_rolls=[random.randint(1, die_sides) for doe in range(5)]
  return die_rolls

def number_games():
  secret=random.randint(1,10)
  guess=int(input("Guess a number between 1 and 10: "))
  if guess==secret:
    return "You won!!!" #return breaks you out of the function
  else:
    return "You lost :("

